FROM openjdk:jdk-alpine

#COPY UsernameAndPass.class /deployments/
#COPY UsernameAndPass$1.class /deployments/
#COPY UsernameAndPass$2.class /deployments/
#COPY UsernameAndPass$3.class /deployments/
#COPY UsernameAndPass$4.class /deployments/
#COPY UsernameAndPass$5.class /deployments/
#COPY UsernameAndPass$6.class /deployments/
#COPY UsernameAndPass$7.class /deployments/
#COPY UsernameAndPass$8.class /deployments/
#COPY UsernameAndPass$8$1.class /deployments/
#COPY UsernameAndPass$9.class /deployments/
#COPY UsernameAndPass$10.class /deployments/
COPY guiClient.class /deployments/
COPY ClientListener.class /deployments/
#COPY User.class /deployments/
#COPY UserAccount.class /deployments/
#COPY UserAccountList.class /deployments/
#COPY Users /deployments/
 
CMD cd /deployments; java UsernameAndPass

